FROM rust:1.92-slim-bookworm

WORKDIR /app

RUN apt-get update && \
    apt-get install -y pkg-config libssl-dev ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch

COPY certs/rootCA.pem /usr/local/share/ca-certificates/rootCA.crt

RUN update-ca-certificates

CMD ["cargo", "watch", "-x", "run -- --config /app/dev/config.toml"]
